name: www.mistriotis.com
url: ""
gems: [jekyll-paginate,  jekyll-gist]
paginate: 8
description: Dimitrios Mistriotis - Personal Site.
intro: Blog posts, contact, project, CV material
#Comment out url when working locally to resolve base urls correctly
#url:

# Owner/author information
owner:
  name: Dimitrios Mistriotis
  email: dimitrios@mistriotis.com

# Links to include in top navigation
# For external links add external: true
